"""Biophysical production and climate module for SEN-HARP.

This first version computes:
- firms' energy requirements;
- renewable and non-renewable energy;
- industrial emissions;
- land-use emissions;
- emissions outside the modelled economy;
- world emissions.

Carbon stocks, temperature and climate damages will be
introduced after the emissions scale has been validated.
"""

from __future__ import annotations

from .entities import Firm
from .parameters import Parameters

import math

def compute_firm_energy_and_emissions(
    firm: Firm,
    params: Parameters,
) -> float:
    """Compute one firm's productive energy use and emissions."""

    if not firm.active:
        firm.energy_intensity = 0.0
        firm.energy_needed = 0.0

        firm.renewable_energy_share = 0.0
        firm.renewable_energy = 0.0
        firm.non_renewable_energy = 0.0

        firm.production_emissions = 0.0

        return 0.0

    green_ratio = min(
        1.0,
        max(
            0.0,
            float(firm.green_capital_ratio),
        ),
    )

    energy_intensity = (
        green_ratio
        * params.green_energy_intensity
        + (
            1.0
            - green_ratio
        )
        * params.brown_energy_intensity
    )

    actual_output = max(
        0.0,
        float(firm.actual_output),
    )

    energy_needed = (
        energy_intensity
        * actual_output
        * params.energy_per_output
    )

    # In the canonical formulation, the renewable-energy
    # share is proxied by the green-capital ratio.
    renewable_energy_share = green_ratio

    renewable_energy = (
        renewable_energy_share
        * energy_needed
    )

    non_renewable_energy = (
        energy_needed
        - renewable_energy
    )

    production_emissions = (
        params.emissions_per_non_renewable_energy
        * non_renewable_energy
    )

    firm.energy_intensity = energy_intensity
    firm.energy_needed = energy_needed

    firm.renewable_energy_share = (
        renewable_energy_share
    )

    firm.renewable_energy = renewable_energy
    firm.non_renewable_energy = (
        non_renewable_energy
    )

    firm.production_emissions = (
        production_emissions
    )

    return production_emissions


def update_climate_emissions(
    firms: list[Firm],
    period: int,
    previous_land_use_emissions: float,
    params: Parameters,
) -> tuple[
    float,
    float,
    float,
    float,
    float,
]:
    """Update production, land-use and world emissions.

    Returns
    -------
    industrial_emissions
        Emissions generated by firms.
    land_use_emissions
        Emissions generated by land-use change.
    modelled_economy_emissions
        Industrial plus land-use emissions.
    rest_of_world_emissions
        Exogenous emissions outside the modelled economy.
    world_emissions
        Global emissions.
    """

    if period < 0:
        raise ValueError(
            "period must be non-negative."
        )

    if (
        params.emissions_per_non_renewable_energy
        < 0.0
    ):
        raise ValueError(
            "emissions_per_non_renewable_energy "
            "cannot be negative."
        )

    if not params.climate_block_enabled:
        for firm in firms:
            compute_firm_energy_and_emissions(
                firm=firm,
                params=params,
            )

            firm.energy_needed = 0.0
            firm.renewable_energy = 0.0
            firm.non_renewable_energy = 0.0
            firm.production_emissions = 0.0

        return (
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
        )

    if not (
        0.0
        <= params.land_use_emissions_decline_rate
        <= 1.0
    ):
        raise ValueError(
            "land_use_emissions_decline_rate must be "
            "between zero and one."
        )

    if params.energy_per_output < 0.0:
        raise ValueError(
            "energy_per_output cannot be negative."
        )

    industrial_emissions = sum(
        compute_firm_energy_and_emissions(
            firm=firm,
            params=params,
        )
        for firm in firms
    )

    if period == 0:
        land_use_emissions = max(
            0.0,
            params.initial_land_use_emissions,
        )
    else:
        land_use_emissions = (
            max(
                0.0,
                previous_land_use_emissions,
            )
            * (
                1.0
                - params
                .land_use_emissions_decline_rate
            )
        )

    modelled_economy_emissions = (
        industrial_emissions
        + land_use_emissions
    )

    rest_of_world_emissions = (
        params.initial_rest_of_world_emissions
        * (
            1.0
            + params.rest_of_world_emissions_growth
        )
        ** period
    )

    rest_of_world_emissions = max(
        0.0,
        rest_of_world_emissions,
    )

    world_emissions = (
        modelled_economy_emissions
        + rest_of_world_emissions
    )

    return (
        industrial_emissions,
        land_use_emissions,
        modelled_economy_emissions,
        rest_of_world_emissions,
        world_emissions,
    )

def compute_climate_damage(
    atmospheric_temperature: float,
    params: Parameters,
) -> tuple[float, float]:
    """Return raw and bounded climate damage."""

    safe_temperature = min(
        max(
            0.0,
            float(atmospheric_temperature),
        ),
        params.maximum_damage_temperature,
    )

    raw_damage = (
        params.climate_damage_eta_1
        * safe_temperature

        + params.climate_damage_eta_2
        * safe_temperature ** 2

        + params.climate_damage_eta_3
        * safe_temperature
        ** params.climate_damage_exponent
    )
    
    if params.climate_damage_exponent <= 0.0:
        raise ValueError(
            "climate_damage_exponent must be positive."
        )

    climate_damage = (
        1.0
        - 1.0 / (
            1.0 + raw_damage
        )
    )

    return (
        raw_damage,
        climate_damage,
    )

def split_lagged_climate_damage(
    lagged_climate_damage: float,
    params: Parameters,
) -> tuple[float, float]:
    """Split lagged climate damage between productivity and capital.

    Returns
    -------
    productivity_damage_rate
        Current-period proportional reduction in productivity.

    capital_damage_rate
        Current-period proportional destruction of opening capital.
    """

    if not 0.0 <= lagged_climate_damage <= 1.0:
        raise ValueError(
            "lagged_climate_damage must be "
            "between zero and one."
        )

    if params.climate_damage_scale < 0.0:
        raise ValueError(
            "climate_damage_scale cannot be negative."
        )

    productivity_share = (
        params.climate_productivity_damage_share
    )

    capital_share = (
        params.climate_capital_damage_share
    )

    if not 0.0 <= productivity_share <= 1.0:
        raise ValueError(
            "climate_productivity_damage_share must be "
            "between zero and one."
        )

    if not 0.0 <= capital_share <= 1.0:
        raise ValueError(
            "climate_capital_damage_share must be "
            "between zero and one."
        )

    if abs(
        productivity_share
        + capital_share
        - 1.0
    ) > 1e-12:
        raise ValueError(
            "Climate productivity and capital damage "
            "shares must sum to one."
        )

    effective_damage = min(
        1.0,
        params.climate_damage_scale
        * lagged_climate_damage,
    )

    productivity_damage_rate = (
        productivity_share
        * effective_damage
    )

    capital_damage_rate = (
        capital_share
        * effective_damage
    )

    return (
        productivity_damage_rate,
        capital_damage_rate,
    )

def update_climate_state(
    period: int,
    world_emissions: float,
    previous_atmospheric_carbon: float,
    previous_upper_ocean_carbon: float,
    previous_lower_ocean_carbon: float,
    previous_exogenous_forcing: float,
    previous_atmospheric_temperature: float,
    previous_lower_ocean_temperature: float,
    params: Parameters,
) -> tuple[
    float,
    float,
    float,
    float,
    float,
    float,
    float,
    float,
    float,
]:
    """Update the end-of-period climate state.

    The previous climate state is the state observed at the
    beginning of the current period. Current-period emissions
    are incorporated into the end-of-period carbon stocks.

    The resulting climate damage will affect production only
    from the following period.
    """

    if period < 0:
        raise ValueError(
            "period must be non-negative."
        )

    if world_emissions < 0.0:
        raise ValueError(
            "world_emissions cannot be negative."
        )

    if params.climate_sensitivity <= 0.0:
        raise ValueError(
            "climate_sensitivity must be positive."
        )

    if (
        params.preindustrial_atmospheric_carbon
        <= 0.0
    ):
        raise ValueError(
            "preindustrial_atmospheric_carbon "
            "must be positive."
        )

    atmospheric_carbon = (
        world_emissions
        + params.climate_phi_11
        * previous_atmospheric_carbon
        + params.climate_phi_21
        * previous_upper_ocean_carbon
    )

    upper_ocean_carbon = (
        params.climate_phi_12
        * previous_atmospheric_carbon
        + params.climate_phi_22
        * previous_upper_ocean_carbon
        + params.climate_phi_32
        * previous_lower_ocean_carbon
    )

    lower_ocean_carbon = (
        params.climate_phi_23
        * previous_upper_ocean_carbon
        + params.climate_phi_33
        * previous_lower_ocean_carbon
    )

    exogenous_forcing = (
        previous_exogenous_forcing
        + params.exogenous_forcing_increment
    )

    carbon_ratio = max(
        atmospheric_carbon
        / params.preindustrial_atmospheric_carbon,
        1e-12,
    )

    radiative_forcing = (
        params.radiative_forcing_for_co2_doubling
        * math.log2(carbon_ratio)
        + exogenous_forcing
    )

    climate_feedback = (
        params.radiative_forcing_for_co2_doubling
        / params.climate_sensitivity
    )

    atmospheric_temperature = (
        previous_atmospheric_temperature
        + params.atmospheric_temperature_adjustment
        * (
            radiative_forcing
            - climate_feedback
            * previous_atmospheric_temperature
            - params.atmosphere_ocean_heat_exchange
            * (
                previous_atmospheric_temperature
                - previous_lower_ocean_temperature
            )
        )
    )

    lower_ocean_temperature = (
        previous_lower_ocean_temperature
        + params.lower_ocean_temperature_adjustment
        * (
            previous_atmospheric_temperature
            - previous_lower_ocean_temperature
        )
    )

    (
        raw_climate_damage,
        climate_damage,
    ) = compute_climate_damage(
        atmospheric_temperature=(
            atmospheric_temperature
        ),
        params=params,
    )

    return (
        atmospheric_carbon,
        upper_ocean_carbon,
        lower_ocean_carbon,
        exogenous_forcing,
        radiative_forcing,
        atmospheric_temperature,
        lower_ocean_temperature,
        raw_climate_damage,
        climate_damage,
    )