from dataclasses import dataclass
from enum import Enum, IntEnum

class Scenario(str, Enum):
    BASELINE = "baseline"
    CARBON_TAX = "carbon_tax"
    GREEN_DEAL = "green_deal"
    POST_GROWTH = "post_growth"

class PolicyMode(str, Enum):
    """Political activation regime for a policy package."""

    OFF = "off"
    FIXED = "fixed"
    ENDOGENOUS = "endogenous"
    
class EmploymentStatus(IntEnum):
    """Employment states used in SEN-HARP."""

    UNEMPLOYED = 0
    LOW_SKILLED_BROWN = 1
    LOW_SKILLED_GREEN = 2
    JOB_GUARANTEE = 3
    HIGH_SKILLED_BROWN = 4
    HIGH_SKILLED_GREEN = 5
    RESKILLING = 6


class SkillLevel(IntEnum):
    """Skill levels used in labour-market matching."""

    LOW_SKILL = 0
    HIGH_SKILL = 1

class Sector(str, Enum):
    """Economic sectors represented in SEN-HARP."""

    AGRICULTURE = "agriculture"
    ENERGY = "energy"
    HOUSING = "housing"
    TRANSPORT = "transport"
    INDUSTRY = "industry"
    TECHNOLOGY = "technology"
    
@dataclass
class Household:
    household_id: int
    peer_group: str
    disposable_income: float
    base_consumption_cost: float
    needs_index: float = 100.0

    employment_status: EmploymentStatus = (
        EmploymentStatus.UNEMPLOYED
    )
    skill_level: SkillLevel = SkillLevel.LOW_SKILL
    employer_id: int = -1
    reskilling_counter: int = 0
    # Bank holding the household's deposit and credit account.
    bank_id: int = -1

    # Current-period economic income
    private_wage_income: float = 0.0
    public_wage_income: float = 0.0
    transfer_income: float = 0.0
    gross_income: float = 0.0

    # Universal basic income received during the current period.
    basic_income_income: float = 0.0
    unemployment_benefit_offset_by_basic_income: float = 0.0
    dividend_income: float = 0.0

    # Household carbon pricing and Green Deal revenue recycling.
    household_carbon_tax_base: float = 0.0
    household_carbon_tax_paid: float = 0.0
    carbon_dividend_income: float = 0.0
    
    # Current-period value of universal basic services
    # effectively received in kind.
    basic_services_received: float = 0.0
    planned_basic_services_received: float = 0.0
    planned_basic_services_public_cost: float = 0.0

    # Essential expenditure still paid privately after delivered UBS.
    # NeedsIndex uses this economic burden, not UBS as a direct bonus.
    constrained_consumption_cost: float | None = None

    # Share of the household's basic consumption cost covered
    # by universal basic services.
    basic_services_coverage: float = 0.0

    # Explicit contribution of UBS to NeedsIndex growth.
    basic_services_component: float = 0.0

    # UBS coverage inherited from the preceding period.
    previous_basic_services_coverage: float = 0.0

    # Current change in UBS coverage.
    basic_services_coverage_change: float = 0.0

    # Household income taxation
    taxable_income: float = 0.0
    income_tax_paid: float = 0.0
    progressive_income_tax_paid: float = 0.0

    # Disposable income generated by the new economic circuit
    economic_disposable_income: float = 0.0
    
    # Current-period household consumption
    desired_consumption: float = 0.0
    essential_consumption: float = 0.0
    supplementary_consumption: float = 0.0
    total_consumption: float = 0.0

    # Household financial stocks and flows
    savings: float = 0.0
    previous_savings: float = 0.0

    new_household_debt: float = 0.0
    household_debt: float = 0.0
    previous_household_debt: float = 0.0

    household_debt_repayment: float = 0.0
    household_debt_interest: float = 0.0

    # Territory:
    # 0 = rural
    # 1 = urban
    territory_id: int = -1

    # Supplementary-consumption preferences
    agriculture_preference: float = 0.0
    energy_preference: float = 0.0
    housing_preference: float = 0.0
    transport_preference: float = 0.0
    industry_preference: float = 0.0
    technology_preference: float = 0.0

    # Essential consumption by sector
    essential_agriculture_consumption: float = 0.0
    essential_energy_consumption: float = 0.0
    essential_housing_consumption: float = 0.0
    essential_transport_consumption: float = 0.0
    essential_industry_consumption: float = 0.0
    essential_technology_consumption: float = 0.0

    # Supplementary consumption by sector
    supplementary_agriculture_consumption: float = 0.0
    supplementary_energy_consumption: float = 0.0
    supplementary_housing_consumption: float = 0.0
    supplementary_transport_consumption: float = 0.0
    supplementary_industry_consumption: float = 0.0
    supplementary_technology_consumption: float = 0.0

    # Total consumption by sector
    agriculture_consumption: float = 0.0
    energy_consumption: float = 0.0
    housing_consumption: float = 0.0
    transport_consumption: float = 0.0
    industry_consumption: float = 0.0
    technology_consumption: float = 0.0

    # =========================================================
    # HOUSEHOLD MARKET SETTLEMENT
    # =========================================================

    # Consumption planned before sectoral rationing.
    planned_essential_consumption: float = 0.0
    planned_supplementary_consumption: float = 0.0
    planned_total_consumption: float = 0.0

    # Consumption not obtained because of sectoral shortages.
    unmet_essential_consumption: float = 0.0
    unmet_supplementary_consumption: float = 0.0
    unmet_total_consumption: float = 0.0

    # Part of current-period credit cancelled because the
    # corresponding consumption could not be realised.
    cancelled_household_credit: float = 0.0

    # Unspent resources returned to household savings after
    # cancellation of unnecessary new credit.
    settlement_refund_to_savings: float = 0.0
    
    # vote
    previous_vote_probability: float = 0.50
    previous_vote: int = 1
    needs_index_at_last_election: float = 100.0
    
    energy_exposure: float = 0.50
    brown_job_exposure: float = 0.50
    green_job_access: float = 0.50
    transfer_weight: float = 0.50
    socialized_service_access: float = 0.50
    
    needs_index_growth: float = 0.0
    vote_probability: float = 0.50
    vote: int = 1
    
    transport_cost: float = 0.0
    distance_to_public_services: float = 0.0
    
    affordability_component: float = 0.0
    relative_income_component: float = 0.0
    public_service_component: float = 0.0
    transport_cost_burden: float = 0.0
  

    # Environmental outcomes
    energy_emissions: float = 0.0
    transport_emissions: float = 0.0
    consumption_emissions: float = 0.0
    total_emissions: float = 0.0

    environmental_damage: float = 0.0

@dataclass
class Firm:
    """A productive firm with green and brown capital."""

    firm_id: int
    sector: Sector
    bank_id: int

    # Structural characteristics
    productivity_factor: float = 1.0

    high_skill_job_share: float = 0.50

    animal_spirits_brown: float = 0.025
    animal_spirits_green: float = 0.025

    gamma_cash_flow: float = 0.01
    gamma_leverage: float = 0.01
    gamma_capacity: float = 0.01
    gamma_interest: float = 0.01

    # Balance-sheet stocks
    brown_capital: float = 0.0
    green_capital: float = 0.0

    brown_loans: float = 0.0
    green_loans: float = 0.0

    # Interest rates
    brown_loan_interest_rate: float = 0.02
    green_loan_interest_rate: float = 0.02
    
    # Opening state inherited from the previous period
    previous_brown_capital: float = 0.0
    previous_green_capital: float = 0.0

    previous_brown_loans: float = 0.0
    previous_green_loans: float = 0.0

    previous_profits: float = 0.0

    previous_brown_loan_interest_rate: float = 0.02
    previous_green_loan_interest_rate: float = 0.02

    # Opening capital before current-period climate destruction.
    opening_brown_capital_before_climate_damage: float = 0.0
    opening_green_capital_before_climate_damage: float = 0.0

    # Productive services received from government-owned
    # public green capital during the current period.
    public_green_capital_service: float = 0.0

    # Current-period climate-capital destruction.
    climate_capital_damage_rate: float = 0.0

    climate_brown_capital_loss: float = 0.0
    climate_green_capital_loss: float = 0.0
    climate_capital_loss: float = 0.0

    # =========================================================
    # PRIVATE INVESTMENT MARKET SETTLEMENT
    # =========================================================

    # Investment and credit granted before goods-market
    # rationing.
    planned_brown_investment: float = 0.0
    planned_green_investment: float = 0.0

    planned_brown_loans_granted: float = 0.0
    planned_green_loans_granted: float = 0.0

    # Investment goods not delivered.
    unmet_brown_investment: float = 0.0
    unmet_green_investment: float = 0.0

    # Credit cancelled because the corresponding investment
    # good was not delivered.
    cancelled_brown_credit: float = 0.0
    cancelled_green_credit: float = 0.0

    
    # Current-period productive capacity
    productivity: float = 0.0
    production_shock: float = 1.0

    potential_output: float = 0.0
    full_capacity_output: float = 0.0

    # Output planned before labour-market matching
    planned_output: float = 0.0

    # Previous-period and demand-based production planning
    previous_planned_output: float = 0.0
    expected_demand: float = 0.0
    desired_output: float = 0.0

    # Total labour demand before technological
    # and skill decomposition
    desired_total_jobs: float = 0.0
    target_total_jobs: int = 0

    # Maximum output permitted by filled employment
    labor_constrained_output: float = 0.0

    # Output effectively realised
    actual_output: float = 0.0


    # =========================================================
    # REALISED SALES
    # =========================================================

    # Share of current output sold during the period.
    sales_ratio: float = 0.0

    # Physical quantity of current output sold.
    sales_quantity: float = 0.0

    # Current production not sold during the period.
    # This is not yet carried forward as an inventory stock.
    unsold_output: float = 0.0
    # Unit costs and prices
    unit_labor_cost: float = 0.0
    price_markup_rate: float = 0.0
    price: float = 0.0

    # Nominal and real household demand addressed to the firm
    household_nominal_demand: float = 0.0
    household_quantity_demand: float = 0.0

    # autres
    energy_needed: float = 0.0

    revenue: float = 0.0
    wage_bill: float = 0.0
    carbon_tax_paid: float = 0.0
    profits: float = 0.0
    profit_tax_paid: float = 0.0
    dividends_paid: float = 0.0
    retained_earnings: float = 0.0

    # =========================================================
    # FIRM INTEREST PAYMENTS
    # =========================================================

    # Interest paid during the current period on opening debt.
    brown_interest_paid: float = 0.0
    green_interest_paid: float = 0.0
    interest_paid: float = 0.0

    # Investment-decision indicators
    cash_flow_ratio: float = 0.0
    investment_leverage: float = 0.0
    investment_capacity_utilization: float = 0.0
    firm_carbon_cost: float = 0.0

    desired_brown_capital_growth: float = 0.0
    desired_green_capital_growth: float = 0.0

    # Desired investment
    desired_brown_investment: float = 0.0
    desired_green_investment: float = 0.0

    brown_self_financed_investment: float = 0.0
    green_self_financed_investment: float = 0.0

    # Loan demand
    brown_loan_demand: float = 0.0
    green_loan_demand: float = 0.0

    # Credit effectively granted
    brown_loans_granted: float = 0.0
    green_loans_granted: float = 0.0

    # Realised investment
    brown_investment: float = 0.0
    green_investment: float = 0.0

    # Capital depreciation and policy-induced retirement
    brown_depreciation: float = 0.0
    green_depreciation: float = 0.0
    brown_policy_retirement: float = 0.0

    # Loan-principal repayment
    brown_loan_repayment: float = 0.0
    green_loan_repayment: float = 0.0

    # Labour demand by technology
    target_brown_jobs: int = 0
    target_green_jobs: int = 0

    # Labour demand by technology and skill
    brown_low_skill_demand: int = 0
    green_low_skill_demand: int = 0
    brown_high_skill_demand: int = 0
    green_high_skill_demand: int = 0

    # Jobs effectively filled after household matching
    brown_low_skill_employment: int = 0
    green_low_skill_employment: int = 0
    brown_high_skill_employment: int = 0
    green_high_skill_employment: int = 0

    # =========================================================
    # BIOPHYSICAL PRODUCTION FLOWS
    # =========================================================

    energy_intensity: float = 0.0
    energy_needed: float = 0.0

    renewable_energy_share: float = 0.0
    renewable_energy: float = 0.0
    non_renewable_energy: float = 0.0

    production_emissions: float = 0.0
    
    # Firm status
    active: bool = True

    @property
    def total_capital(self) -> float:
        """Return total productive capital."""

        return self.brown_capital + self.green_capital

    @property
    def total_debt(self) -> float:
        """Return total bank debt."""

        return self.brown_loans + self.green_loans

    @property
    def green_capital_ratio(self) -> float:
        """Return the green share of productive capital."""

        if self.total_capital <= 0.0:
            return 0.0

        return self.green_capital / self.total_capital
    
    @property
    def productive_green_capital(self) -> float:
        """Green capital effectively available for production."""
        return (
            self.green_capital
            + max(
                0.0,
                self.public_green_capital_service,
            )
        )


    @property
    def productive_total_capital(self) -> float:
        """Private capital plus public green-capital services."""

        return (
            self.brown_capital
            + self.productive_green_capital
        )


    @property
    def productive_green_capital_ratio(self) -> float:
        """Green share of capital effectively used in production."""

        if self.productive_total_capital <= 0.0:
            return 0.0

        return (
            self.productive_green_capital
            / self.productive_total_capital
        )

    @property
    def leverage(self) -> float:
        """Return the firm's debt-to-capital ratio."""

        if self.total_capital <= 0.0:
            return 0.0

        return self.total_debt / self.total_capital

    @property
    def total_employment(self) -> int:
        """Return total employment in the firm."""

        return (
            self.brown_low_skill_employment
            + self.green_low_skill_employment
            + self.brown_high_skill_employment
            + self.green_high_skill_employment
        )

    @property
    def green_employment(self) -> int:
        """Return green employment in the firm."""

        return (
            self.green_low_skill_employment
            + self.green_high_skill_employment
        )

    @property
    def brown_employment(self) -> int:
        """Return brown employment in the firm."""

        return (
            self.brown_low_skill_employment
            + self.brown_high_skill_employment
        )

@dataclass
class Bank:
    """A commercial bank financing productive firms."""

    bank_id: int

    target_leverage: float = 2.0
    animal_spirits: float = 1.0
    risk_appetite: float = 0.82
    market_share: float = 0.0

    green_loans: float = 0.0
    brown_loans: float = 0.0

    # =========================================================
    # BANK LOANS TO FIRMS
    # =========================================================

    # Opening stocks of bank loans to firms.
    previous_brown_loans: float = 0.0
    previous_green_loans: float = 0.0

    # New loans effectively used for delivered investment.
    new_brown_loans: float = 0.0
    new_green_loans: float = 0.0

    # Repayment of firm-loan principal.
    brown_loan_repayments: float = 0.0
    green_loan_repayments: float = 0.0

    # Interest received from firms.
    # This remains zero until firm interest payments are activated.
    firm_loan_interest_income: float = 0.0

    reserves: float = 0.0
    government_bonds: float = 0.0
    equity: float = 0.0

    interest_on_reserves: float = 0.0

    # =========================================================
    # GOVERNMENT-BOND HOLDINGS
    # =========================================================

    # Government bonds held at the beginning of the period.
    previous_government_bonds: float = 0.0

    # Signed change in government-bond holdings during the
    # current period. A negative value represents redemption
    # or sale of bonds.
    government_bond_change: float = 0.0

    # Interest received on opening government-bond holdings.
    government_bond_interest_income: float = 0.0

    # Household consumer-credit stocks and flows
    previous_consumer_loans: float = 0.0
    new_consumer_loans: float = 0.0
    consumer_loan_repayments: float = 0.0
    consumer_loans: float = 0.0

    # Current-period interest received from households
    consumer_loan_interest_income: float = 0.0

    # =========================================================
    # HOUSEHOLD DEPOSITS
    # =========================================================

    # Opening household-deposit liabilities.
    previous_household_deposits: float = 0.0

    # Closing household-deposit liabilities.
    household_deposits: float = 0.0

    # Current-period change in household deposits.
    household_deposit_change: float = 0.0

    @property
    def total_firm_loans(self) -> float:
        """Return total loans granted to firms."""

        return self.green_loans + self.brown_loans

@dataclass
class CentralBank:
    """The central bank and its main monetary-policy accounts."""

    policy_rate: float = 0.02

    green_policy_rate: float = 0.02
    brown_policy_rate: float = 0.02
    reserve_rate: float = 0.02

    government_bonds: float = 0.0
    bank_reserves: float = 0.0
    government_account: float = 0.0

    # =========================================================
    # CENTRAL-BANK GOVERNMENT-BOND HOLDINGS
    # =========================================================

    previous_government_bonds: float = 0.0
    government_bond_change: float = 0.0
    government_bond_interest_income: float = 0.0

@dataclass
class Government:
    """Public-sector flows and balance-sheet state."""

    taxes_households: float = 0.0
    taxes_firms: float = 0.0
    carbon_tax_revenue: float = 0.0
    firm_carbon_tax_revenue: float = 0.0
    household_carbon_tax_revenue: float = 0.0
    carbon_dividend_spending: float = 0.0

    current_spending: float = 0.0
    capital_spending: float = 0.0

    primary_deficit: float = 0.0
    interest_payment: float = 0.0
    deficit: float = 0.0

    public_debt: float = 0.0
    government_interest_rate: float = 0.02

    # =========================================================
    # PUBLIC DEBT ACCUMULATION
    # =========================================================

    # Public-debt stock at the beginning of the period.
    previous_public_debt: float = 0.0

    # Change in the public-debt stock during the period.
    public_debt_change: float = 0.0

    # Surplus remaining after complete repayment of public debt.
    excess_surplus_after_debt_repayment: float = 0.0

    # Detailed current-period public accounts
    total_revenue: float = 0.0

    transfer_spending: float = 0.0
    public_wage_spending: float = 0.0
    # Gross public spending on the post-growth basic income.
    basic_income_spending: float = 0.0

    # =========================================================
    # POST-GROWTH UNIVERSAL BASIC SERVICES
    # =========================================================

    # Current purchases before the additional UBS programme.
    base_current_purchases: float = 0.0

    # UBS expenditure before and after market settlement.
    planned_basic_services_spending: float = 0.0
    realised_basic_services_spending: float = 0.0
    unmet_basic_services_spending: float = 0.0
    basic_services_admin_price_factor: float = 1.0

    # Direct purchases from firms
    current_purchases: float = 0.0
    capital_purchases: float = 0.0

    # Benchmark calibrated at the initial period.
    initial_public_purchase_budget: float | None = None

    # =========================================================
    # GREEN DEAL PUBLIC INVESTMENT
    # =========================================================

    # Ordinary capital purchases planned before adding the
    # Green Deal instrument.
    base_capital_purchases: float = 0.0

    # Additional public green investment.
    planned_public_green_investment: float = 0.0
    realised_public_green_investment: float = 0.0
    unmet_public_green_investment: float = 0.0

    # Government-owned public green-capital stock.
    public_green_capital: float = 0.0
    public_green_capital_depreciation: float = 0.0
    
    # =========================================================
    # GOVERNMENT MARKET SETTLEMENT
    # =========================================================

    # Purchases planned before sectoral rationing.
    planned_current_purchases: float = 0.0
    planned_capital_purchases: float = 0.0

    # Purchases effectively delivered and paid.
    realised_current_purchases: float = 0.0
    realised_capital_purchases: float = 0.0

    # Purchases not delivered because of sectoral shortages.
    unmet_current_purchases: float = 0.0
    unmet_capital_purchases: float = 0.0

@dataclass
class PolicyState:
    scenario: Scenario
    active: bool = True
    support_share: float = 1.0
    consecutive_active_periods: int = 0
