"""Sectoral demand generated by firm investment."""

from .entities import Firm
from .parameters import Parameters


def validate_investment_supplier_shares(
    params: Parameters,
) -> None:
    """Validate brown and green supplier-sector shares."""

    brown_share_sum = (
        params.brown_investment_housing_share
        + params.brown_investment_industry_share
        + params.brown_investment_technology_share
    )

    green_share_sum = (
        params.green_investment_housing_share
        + params.green_investment_industry_share
        + params.green_investment_technology_share
    )

    if abs(brown_share_sum - 1.0) > 1e-12:
        raise ValueError(
            "Brown investment supplier shares "
            "must sum to one."
        )

    if abs(green_share_sum - 1.0) > 1e-12:
        raise ValueError(
            "Green investment supplier shares "
            "must sum to one."
        )

    share_values = [
        params.brown_investment_housing_share,
        params.brown_investment_industry_share,
        params.brown_investment_technology_share,
        params.green_investment_housing_share,
        params.green_investment_industry_share,
        params.green_investment_technology_share,
    ]

    if any(
        share < 0.0 or share > 1.0
        for share in share_values
    ):
        raise ValueError(
            "Investment supplier shares must be "
            "between zero and one."
        )


def compute_sector_investment_demand(
    firms: list[Firm],
    params: Parameters,
) -> dict[str, float]:
    """Allocate realised investment expenditure to supplier sectors.

    Brown and green investment are interpreted as nominal
    expenditure at replacement cost.
    """

    validate_investment_supplier_shares(
        params=params,
    )

    total_brown_investment = sum(
        max(
            0.0,
            firm.brown_investment,
        )
        for firm in firms
        if firm.active
    )

    total_green_investment = sum(
        max(
            0.0,
            firm.green_investment,
        )
        for firm in firms
        if firm.active
    )

    agriculture_investment_demand = 0.0
    energy_investment_demand = 0.0
    housing_investment_demand = (
        total_brown_investment
        * params.brown_investment_housing_share
        + total_green_investment
        * params.green_investment_housing_share
    )
    transport_investment_demand = 0.0

    industry_investment_demand = (
        total_brown_investment
        * params.brown_investment_industry_share
        + total_green_investment
        * params.green_investment_industry_share
    )

    technology_investment_demand = (
        total_brown_investment
        * params.brown_investment_technology_share
        + total_green_investment
        * params.green_investment_technology_share
    )

    total_firm_investment = (
        total_brown_investment
        + total_green_investment
    )

    total_sector_investment_demand = (
        agriculture_investment_demand
        + energy_investment_demand
        + housing_investment_demand
        + transport_investment_demand
        + industry_investment_demand
        + technology_investment_demand
    )

    return {
        "total_brown_investment": (
            total_brown_investment
        ),

        "total_green_investment": (
            total_green_investment
        ),

        "total_firm_investment": (
            total_firm_investment
        ),

        "agriculture_investment_demand": (
            agriculture_investment_demand
        ),

        "energy_investment_demand": (
            energy_investment_demand
        ),

        "housing_investment_demand": (
            housing_investment_demand
        ),

        "transport_investment_demand": (
            transport_investment_demand
        ),

        "industry_investment_demand": (
            industry_investment_demand
        ),

        "technology_investment_demand": (
            technology_investment_demand
        ),

        "total_sector_investment_demand": (
            total_sector_investment_demand
        ),

        "investment_allocation_gap": (
            total_firm_investment
            - total_sector_investment_demand
        ),
    }
